#!/bin/sh

## hyphop ##

echo "[i] $0 BEGIN"


./autogen.sh

## ignore 
## configure: error: a2x is required to build docs, install asciidoc
## need `apt-get install asciidoc`

set -e 

./configure --disable-docs

make

echo "[i] $0 END"

exit 0
